/* tslint:disable */
/* eslint-disable */
/**
 * PokerEvents.Api, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  EventDetailsDto,
  LiveReportingDetailsDto,
  ProblemDetails,
  Result,
} from '../models/index';
import {
    EventDetailsDtoFromJSON,
    EventDetailsDtoToJSON,
    LiveReportingDetailsDtoFromJSON,
    LiveReportingDetailsDtoToJSON,
    ProblemDetailsFromJSON,
    ProblemDetailsToJSON,
    ResultFromJSON,
    ResultToJSON,
} from '../models/index';

export interface ApiEmbeddedEventsEventIdGetRequest {
    eventId: string;
}

export interface ApiEmbeddedLivereportingsLiveReportingIdGetRequest {
    liveReportingId: string;
}

/**
 * 
 */
export class EmbeddedApi extends runtime.BaseAPI {

    /**
     */
    async apiEmbeddedEventsEventIdGetRaw(requestParameters: ApiEmbeddedEventsEventIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EventDetailsDto>> {
        if (requestParameters['eventId'] == null) {
            throw new runtime.RequiredError(
                'eventId',
                'Required parameter "eventId" was null or undefined when calling apiEmbeddedEventsEventIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            queryParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // bearer authentication
        }

        const response = await this.request({
            path: `/api/Embedded/events/{eventId}`.replace(`{${"eventId"}}`, encodeURIComponent(String(requestParameters['eventId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EventDetailsDtoFromJSON(jsonValue));
    }

    /**
     */
    async apiEmbeddedEventsEventIdGet(requestParameters: ApiEmbeddedEventsEventIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EventDetailsDto> {
        const response = await this.apiEmbeddedEventsEventIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiEmbeddedLivereportingsLiveReportingIdGetRaw(requestParameters: ApiEmbeddedLivereportingsLiveReportingIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<LiveReportingDetailsDto>> {
        if (requestParameters['liveReportingId'] == null) {
            throw new runtime.RequiredError(
                'liveReportingId',
                'Required parameter "liveReportingId" was null or undefined when calling apiEmbeddedLivereportingsLiveReportingIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            queryParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // bearer authentication
        }

        const response = await this.request({
            path: `/api/Embedded/livereportings/{liveReportingId}`.replace(`{${"liveReportingId"}}`, encodeURIComponent(String(requestParameters['liveReportingId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => LiveReportingDetailsDtoFromJSON(jsonValue));
    }

    /**
     */
    async apiEmbeddedLivereportingsLiveReportingIdGet(requestParameters: ApiEmbeddedLivereportingsLiveReportingIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<LiveReportingDetailsDto> {
        const response = await this.apiEmbeddedLivereportingsLiveReportingIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
