/* tslint:disable */
/* eslint-disable */
/**
 * PokerEvents.Api, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DayEntity
 */
export interface DayEntity {
    /**
     * 
     * @type {string}
     * @memberof DayEntity
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof DayEntity
     */
    eventId?: string;
    /**
     * 
     * @type {string}
     * @memberof DayEntity
     */
    name?: string;
    /**
     * 
     * @type {Date}
     * @memberof DayEntity
     */
    date?: Date;
}

/**
 * Check if a given object implements the DayEntity interface.
 */
export function instanceOfDayEntity(value: object): boolean {
    return true;
}

export function DayEntityFromJSON(json: any): DayEntity {
    return DayEntityFromJSONTyped(json, false);
}

export function DayEntityFromJSONTyped(json: any, ignoreDiscriminator: boolean): DayEntity {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'eventId': json['eventId'] == null ? undefined : json['eventId'],
        'name': json['name'] == null ? undefined : json['name'],
        'date': json['date'] == null ? undefined : (new Date(json['date'])),
    };
}

export function DayEntityToJSON(value?: DayEntity | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'eventId': value['eventId'],
        'name': value['name'],
        'date': value['date'] == null ? undefined : ((value['date']).toISOString().substring(0,10)),
    };
}

