/* tslint:disable */
/* eslint-disable */
/**
 * PokerEvents.Api, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum ErrorTypes {
    AlreadyExists = 'AlreadyExists',
    Empty = 'Empty',
    JsonParseFailure = 'JsonParseFailure',
    NotFound = 'NotFound',
    Required = 'Required',
    OutOfRange = 'OutOfRange',
    BadRequest = 'BadRequest',
    ThmError = 'ThmError'
}


export function instanceOfErrorTypes(value: any): boolean {
    return Object.values(ErrorTypes).includes(value);
}

export function ErrorTypesFromJSON(json: any): ErrorTypes {
    return ErrorTypesFromJSONTyped(json, false);
}

export function ErrorTypesFromJSONTyped(json: any, ignoreDiscriminator: boolean): ErrorTypes {
    return json as ErrorTypes;
}

export function ErrorTypesToJSON(value?: ErrorTypes | null): any {
    return value as any;
}

