/* tslint:disable */
/* eslint-disable */
/**
 * PokerEvents.Api, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { LiveReportingStatisticsDto } from './LiveReportingStatisticsDto';
import {
    LiveReportingStatisticsDtoFromJSON,
    LiveReportingStatisticsDtoFromJSONTyped,
    LiveReportingStatisticsDtoToJSON,
} from './LiveReportingStatisticsDto';
import type { StateType } from './StateType';
import {
    StateTypeFromJSON,
    StateTypeFromJSONTyped,
    StateTypeToJSON,
} from './StateType';

/**
 * 
 * @export
 * @interface LiveReportingSummaryDto
 */
export interface LiveReportingSummaryDto {
    /**
     * 
     * @type {string}
     * @memberof LiveReportingSummaryDto
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof LiveReportingSummaryDto
     */
    eventId?: string;
    /**
     * 
     * @type {string}
     * @memberof LiveReportingSummaryDto
     */
    dayId?: string;
    /**
     * 
     * @type {string}
     * @memberof LiveReportingSummaryDto
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof LiveReportingSummaryDto
     */
    description?: string;
    /**
     * 
     * @type {StateType}
     * @memberof LiveReportingSummaryDto
     */
    state?: StateType;
    /**
     * 
     * @type {Date}
     * @memberof LiveReportingSummaryDto
     */
    startsAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof LiveReportingSummaryDto
     */
    finishedAt?: Date;
    /**
     * 
     * @type {LiveReportingStatisticsDto}
     * @memberof LiveReportingSummaryDto
     */
    statistics?: LiveReportingStatisticsDto;
    /**
     * 
     * @type {number}
     * @memberof LiveReportingSummaryDto
     */
    updatesCount?: number;
}

/**
 * Check if a given object implements the LiveReportingSummaryDto interface.
 */
export function instanceOfLiveReportingSummaryDto(value: object): boolean {
    return true;
}

export function LiveReportingSummaryDtoFromJSON(json: any): LiveReportingSummaryDto {
    return LiveReportingSummaryDtoFromJSONTyped(json, false);
}

export function LiveReportingSummaryDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): LiveReportingSummaryDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'eventId': json['eventId'] == null ? undefined : json['eventId'],
        'dayId': json['dayId'] == null ? undefined : json['dayId'],
        'name': json['name'] == null ? undefined : json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'state': json['state'] == null ? undefined : StateTypeFromJSON(json['state']),
        'startsAt': json['startsAt'] == null ? undefined : (new Date(json['startsAt'])),
        'finishedAt': json['finishedAt'] == null ? undefined : (new Date(json['finishedAt'])),
        'statistics': json['statistics'] == null ? undefined : LiveReportingStatisticsDtoFromJSON(json['statistics']),
        'updatesCount': json['updatesCount'] == null ? undefined : json['updatesCount'],
    };
}

export function LiveReportingSummaryDtoToJSON(value?: LiveReportingSummaryDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'eventId': value['eventId'],
        'dayId': value['dayId'],
        'name': value['name'],
        'description': value['description'],
        'state': StateTypeToJSON(value['state']),
        'startsAt': value['startsAt'] == null ? undefined : ((value['startsAt'] as any).toISOString()),
        'finishedAt': value['finishedAt'] == null ? undefined : ((value['finishedAt'] as any).toISOString()),
        'statistics': LiveReportingStatisticsDtoToJSON(value['statistics']),
        'updatesCount': value['updatesCount'],
    };
}

