/* tslint:disable */
/* eslint-disable */
/**
 * PokerEvents.Api, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MemoryCacheStatistics
 */
export interface MemoryCacheStatistics {
    /**
     * 
     * @type {number}
     * @memberof MemoryCacheStatistics
     */
    currentEntryCount?: number;
    /**
     * 
     * @type {number}
     * @memberof MemoryCacheStatistics
     */
    currentEstimatedSize?: number;
    /**
     * 
     * @type {number}
     * @memberof MemoryCacheStatistics
     */
    totalMisses?: number;
    /**
     * 
     * @type {number}
     * @memberof MemoryCacheStatistics
     */
    totalHits?: number;
}

/**
 * Check if a given object implements the MemoryCacheStatistics interface.
 */
export function instanceOfMemoryCacheStatistics(value: object): boolean {
    return true;
}

export function MemoryCacheStatisticsFromJSON(json: any): MemoryCacheStatistics {
    return MemoryCacheStatisticsFromJSONTyped(json, false);
}

export function MemoryCacheStatisticsFromJSONTyped(json: any, ignoreDiscriminator: boolean): MemoryCacheStatistics {
    if (json == null) {
        return json;
    }
    return {
        
        'currentEntryCount': json['currentEntryCount'] == null ? undefined : json['currentEntryCount'],
        'currentEstimatedSize': json['currentEstimatedSize'] == null ? undefined : json['currentEstimatedSize'],
        'totalMisses': json['totalMisses'] == null ? undefined : json['totalMisses'],
        'totalHits': json['totalHits'] == null ? undefined : json['totalHits'],
    };
}

export function MemoryCacheStatisticsToJSON(value?: MemoryCacheStatistics | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'currentEntryCount': value['currentEntryCount'],
        'currentEstimatedSize': value['currentEstimatedSize'],
        'totalMisses': value['totalMisses'],
        'totalHits': value['totalHits'],
    };
}

