/* tslint:disable */
/* eslint-disable */
/**
 * PokerEvents.Api, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PlayerEntity
 */
export interface PlayerEntity {
    /**
     * 
     * @type {string}
     * @memberof PlayerEntity
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof PlayerEntity
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof PlayerEntity
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof PlayerEntity
     */
    nickname?: string;
    /**
     * 
     * @type {string}
     * @memberof PlayerEntity
     */
    countryIso?: string;
    /**
     * 
     * @type {string}
     * @memberof PlayerEntity
     */
    photoUrl?: string;
    /**
     * 
     * @type {string}
     * @memberof PlayerEntity
     */
    thmId?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof PlayerEntity
     */
    photos?: Array<string>;
}

/**
 * Check if a given object implements the PlayerEntity interface.
 */
export function instanceOfPlayerEntity(value: object): boolean {
    return true;
}

export function PlayerEntityFromJSON(json: any): PlayerEntity {
    return PlayerEntityFromJSONTyped(json, false);
}

export function PlayerEntityFromJSONTyped(json: any, ignoreDiscriminator: boolean): PlayerEntity {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'nickname': json['nickname'] == null ? undefined : json['nickname'],
        'countryIso': json['countryIso'] == null ? undefined : json['countryIso'],
        'photoUrl': json['photoUrl'] == null ? undefined : json['photoUrl'],
        'thmId': json['thmId'] == null ? undefined : json['thmId'],
        'photos': json['photos'] == null ? undefined : json['photos'],
    };
}

export function PlayerEntityToJSON(value?: PlayerEntity | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'name': value['name'],
        'description': value['description'],
        'nickname': value['nickname'],
        'countryIso': value['countryIso'],
        'photoUrl': value['photoUrl'],
        'thmId': value['thmId'],
        'photos': value['photos'],
    };
}

