/* tslint:disable */
/* eslint-disable */
/**
 * PokerEvents.Api, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PlayerSummaryDto
 */
export interface PlayerSummaryDto {
    /**
     * 
     * @type {string}
     * @memberof PlayerSummaryDto
     */
    playerId?: string;
    /**
     * 
     * @type {string}
     * @memberof PlayerSummaryDto
     */
    thmId?: string;
    /**
     * 
     * @type {string}
     * @memberof PlayerSummaryDto
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof PlayerSummaryDto
     */
    countryIso?: string;
    /**
     * 
     * @type {string}
     * @memberof PlayerSummaryDto
     */
    photoUrl?: string;
}

/**
 * Check if a given object implements the PlayerSummaryDto interface.
 */
export function instanceOfPlayerSummaryDto(value: object): boolean {
    return true;
}

export function PlayerSummaryDtoFromJSON(json: any): PlayerSummaryDto {
    return PlayerSummaryDtoFromJSONTyped(json, false);
}

export function PlayerSummaryDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PlayerSummaryDto {
    if (json == null) {
        return json;
    }
    return {
        
        'playerId': json['playerId'] == null ? undefined : json['playerId'],
        'thmId': json['thmId'] == null ? undefined : json['thmId'],
        'name': json['name'] == null ? undefined : json['name'],
        'countryIso': json['countryIso'] == null ? undefined : json['countryIso'],
        'photoUrl': json['photoUrl'] == null ? undefined : json['photoUrl'],
    };
}

export function PlayerSummaryDtoToJSON(value?: PlayerSummaryDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'playerId': value['playerId'],
        'thmId': value['thmId'],
        'name': value['name'],
        'countryIso': value['countryIso'],
        'photoUrl': value['photoUrl'],
    };
}

