/* tslint:disable */
/* eslint-disable */
/**
 * PokerEvents.Api, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum StateType {
    Draft = 'Draft',
    UpComing = 'UpComing',
    Live = 'Live',
    Finished = 'Finished',
    Archived = 'Archived'
}


export function instanceOfStateType(value: any): boolean {
    return Object.values(StateType).includes(value);
}

export function StateTypeFromJSON(json: any): StateType {
    return StateTypeFromJSONTyped(json, false);
}

export function StateTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): StateType {
    return json as StateType;
}

export function StateTypeToJSON(value?: StateType | null): any {
    return value as any;
}

