/* tslint:disable */
/* eslint-disable */
/**
 * PokerEvents.Api, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TourDto
 */
export interface TourDto {
    /**
     * 
     * @type {string}
     * @memberof TourDto
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof TourDto
     */
    name?: string;
    /**
     * 
     * @type {any}
     * @memberof TourDto
     */
    description?: any;
    /**
     * 
     * @type {string}
     * @memberof TourDto
     */
    abbr?: string;
    /**
     * 
     * @type {string}
     * @memberof TourDto
     */
    logo?: string;
    /**
     * 
     * @type {string}
     * @memberof TourDto
     */
    web?: string;
    /**
     * 
     * @type {string}
     * @memberof TourDto
     */
    thmid?: string;
}

/**
 * Check if a given object implements the TourDto interface.
 */
export function instanceOfTourDto(value: object): boolean {
    return true;
}

export function TourDtoFromJSON(json: any): TourDto {
    return TourDtoFromJSONTyped(json, false);
}

export function TourDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): TourDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'abbr': json['abbr'] == null ? undefined : json['abbr'],
        'logo': json['logo'] == null ? undefined : json['logo'],
        'web': json['web'] == null ? undefined : json['web'],
        'thmid': json['thmid'] == null ? undefined : json['thmid'],
    };
}

export function TourDtoToJSON(value?: TourDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'name': value['name'],
        'description': value['description'],
        'abbr': value['abbr'],
        'logo': value['logo'],
        'web': value['web'],
        'thmid': value['thmid'],
    };
}

