/* tslint:disable */
/* eslint-disable */
/**
 * PokerEvents.Api, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface VenueDto
 */
export interface VenueDto {
    /**
     * 
     * @type {string}
     * @memberof VenueDto
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof VenueDto
     */
    thmId?: string;
    /**
     * 
     * @type {string}
     * @memberof VenueDto
     */
    link?: string;
    /**
     * 
     * @type {string}
     * @memberof VenueDto
     */
    city?: string;
    /**
     * 
     * @type {string}
     * @memberof VenueDto
     */
    country?: string;
    /**
     * 
     * @type {string}
     * @memberof VenueDto
     */
    countryCode?: string;
}

/**
 * Check if a given object implements the VenueDto interface.
 */
export function instanceOfVenueDto(value: object): boolean {
    return true;
}

export function VenueDtoFromJSON(json: any): VenueDto {
    return VenueDtoFromJSONTyped(json, false);
}

export function VenueDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): VenueDto {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'thmId': json['thmId'] == null ? undefined : json['thmId'],
        'link': json['link'] == null ? undefined : json['link'],
        'city': json['city'] == null ? undefined : json['city'],
        'country': json['country'] == null ? undefined : json['country'],
        'countryCode': json['countryCode'] == null ? undefined : json['countryCode'],
    };
}

export function VenueDtoToJSON(value?: VenueDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'name': value['name'],
        'thmId': value['thmId'],
        'link': value['link'],
        'city': value['city'],
        'country': value['country'],
        'countryCode': value['countryCode'],
    };
}

