/* tslint:disable */
/* eslint-disable */
/**
 * PokerEvents.Api, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface VenueDetailsDto
 */
export interface VenueDetailsDto {
    /**
     * 
     * @type {string}
     * @memberof VenueDetailsDto
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof VenueDetailsDto
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof VenueDetailsDto
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof VenueDetailsDto
     */
    summary?: string;
    /**
     * 
     * @type {string}
     * @memberof VenueDetailsDto
     */
    countryIso?: string;
    /**
     * 
     * @type {string}
     * @memberof VenueDetailsDto
     */
    city?: string;
    /**
     * 
     * @type {string}
     * @memberof VenueDetailsDto
     */
    address?: string;
    /**
     * 
     * @type {string}
     * @memberof VenueDetailsDto
     */
    phone?: string;
    /**
     * 
     * @type {string}
     * @memberof VenueDetailsDto
     */
    email?: string;
    /**
     * 
     * @type {string}
     * @memberof VenueDetailsDto
     */
    websiteUrl?: string;
    /**
     * 
     * @type {string}
     * @memberof VenueDetailsDto
     */
    logoUrl?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof VenueDetailsDto
     */
    photos?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof VenueDetailsDto
     */
    thmId?: string;
}

/**
 * Check if a given object implements the VenueDetailsDto interface.
 */
export function instanceOfVenueDetailsDto(value: object): boolean {
    return true;
}

export function VenueDetailsDtoFromJSON(json: any): VenueDetailsDto {
    return VenueDetailsDtoFromJSONTyped(json, false);
}

export function VenueDetailsDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): VenueDetailsDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'summary': json['summary'] == null ? undefined : json['summary'],
        'countryIso': json['countryIso'] == null ? undefined : json['countryIso'],
        'city': json['city'] == null ? undefined : json['city'],
        'address': json['address'] == null ? undefined : json['address'],
        'phone': json['phone'] == null ? undefined : json['phone'],
        'email': json['email'] == null ? undefined : json['email'],
        'websiteUrl': json['websiteUrl'] == null ? undefined : json['websiteUrl'],
        'logoUrl': json['logoUrl'] == null ? undefined : json['logoUrl'],
        'photos': json['photos'] == null ? undefined : json['photos'],
        'thmId': json['thmId'] == null ? undefined : json['thmId'],
    };
}

export function VenueDetailsDtoToJSON(value?: VenueDetailsDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'name': value['name'],
        'description': value['description'],
        'summary': value['summary'],
        'countryIso': value['countryIso'],
        'city': value['city'],
        'address': value['address'],
        'phone': value['phone'],
        'email': value['email'],
        'websiteUrl': value['websiteUrl'],
        'logoUrl': value['logoUrl'],
        'photos': value['photos'],
        'thmId': value['thmId'],
    };
}

