/* tslint:disable */
/* eslint-disable */
/**
 * PokerEvents.Api, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { BlindLevelType } from './blind-level-type';

/**
 * 
 * @export
 * @interface BlindLevelDto
 */
export interface BlindLevelDto {
    /**
     * 
     * @type {string}
     * @memberof BlindLevelDto
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof BlindLevelDto
     */
    'eventId'?: string;
    /**
     * 
     * @type {BlindLevelType}
     * @memberof BlindLevelDto
     */
    'type'?: BlindLevelType;
    /**
     * 
     * @type {number}
     * @memberof BlindLevelDto
     */
    'order'?: number;
    /**
     * 
     * @type {number}
     * @memberof BlindLevelDto
     */
    'number'?: number | null;
    /**
     * 
     * @type {string}
     * @memberof BlindLevelDto
     */
    'name'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof BlindLevelDto
     */
    'description'?: string | null;
    /**
     * 
     * @type {number}
     * @memberof BlindLevelDto
     */
    'smallBlind'?: number | null;
    /**
     * 
     * @type {number}
     * @memberof BlindLevelDto
     */
    'bigBlind'?: number | null;
    /**
     * 
     * @type {number}
     * @memberof BlindLevelDto
     */
    'ante'?: number | null;
    /**
     * 
     * @type {number}
     * @memberof BlindLevelDto
     */
    'durationInMinutes'?: number | null;
}



