/* tslint:disable */
/* eslint-disable */
/**
 * PokerEvents.Api, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface BlindLevelImportDto
 */
export interface BlindLevelImportDto {
    /**
     * 
     * @type {number}
     * @memberof BlindLevelImportDto
     */
    'number'?: number | null;
    /**
     * 
     * @type {number}
     * @memberof BlindLevelImportDto
     */
    'smallBlind'?: number;
    /**
     * 
     * @type {number}
     * @memberof BlindLevelImportDto
     */
    'bigBlind'?: number;
    /**
     * 
     * @type {number}
     * @memberof BlindLevelImportDto
     */
    'ante'?: number | null;
}

