/* tslint:disable */
/* eslint-disable */
/**
 * PokerEvents.Api, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { ChipCountDto } from './chip-count-dto';
// May contain unused imports in some cases
// @ts-ignore
import { RegistrationEntity } from './registration-entity';

/**
 * 
 * @export
 * @interface ChipCountUpdateEntity
 */
export interface ChipCountUpdateEntity {
    /**
     * 
     * @type {string}
     * @memberof ChipCountUpdateEntity
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof ChipCountUpdateEntity
     */
    'registrationId'?: string;
    /**
     * 
     * @type {ChipCountDto}
     * @memberof ChipCountUpdateEntity
     */
    'chipCount'?: ChipCountDto;
    /**
     * 
     * @type {RegistrationEntity}
     * @memberof ChipCountUpdateEntity
     */
    'registration'?: RegistrationEntity;
}

