/* tslint:disable */
/* eslint-disable */
/**
 * PokerEvents.Api, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { EventOverview } from './event-overview';
// May contain unused imports in some cases
// @ts-ignore
import { FestivalState } from './festival-state';

/**
 * 
 * @export
 * @interface FestivalOverviewDto
 */
export interface FestivalOverviewDto {
    /**
     * 
     * @type {string}
     * @memberof FestivalOverviewDto
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof FestivalOverviewDto
     */
    'name': string | null;
    /**
     * 
     * @type {string}
     * @memberof FestivalOverviewDto
     */
    'fromDate'?: string;
    /**
     * 
     * @type {string}
     * @memberof FestivalOverviewDto
     */
    'toDate'?: string;
    /**
     * 
     * @type {string}
     * @memberof FestivalOverviewDto
     */
    'websiteUrl'?: string | null;
    /**
     * 
     * @type {FestivalState}
     * @memberof FestivalOverviewDto
     */
    'state'?: FestivalState;
    /**
     * 
     * @type {Array<EventOverview>}
     * @memberof FestivalOverviewDto
     */
    'events': Array<EventOverview> | null;
}



