/* tslint:disable */
/* eslint-disable */
/**
 * PokerEvents.Api, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface FestivalEntity
 */
export interface FestivalEntity {
    /**
     * 
     * @type {string}
     * @memberof FestivalEntity
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof FestivalEntity
     */
    'seasonId'?: string;
    /**
     * 
     * @type {string}
     * @memberof FestivalEntity
     */
    'venueId'?: string;
    /**
     * 
     * @type {string}
     * @memberof FestivalEntity
     */
    'name'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof FestivalEntity
     */
    'description'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof FestivalEntity
     */
    'fromDate'?: string;
    /**
     * 
     * @type {string}
     * @memberof FestivalEntity
     */
    'toDate'?: string;
    /**
     * 
     * @type {string}
     * @memberof FestivalEntity
     */
    'countryIso'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof FestivalEntity
     */
    'websiteUrl'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof FestivalEntity
     */
    'thmId'?: string | null;
}

