/* tslint:disable */
/* eslint-disable */
/**
 * PokerEvents.Api, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ImageDto
 */
export interface ImageDto {
    /**
     * 
     * @type {string}
     * @memberof ImageDto
     */
    'name'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ImageDto
     */
    'createdAt'?: string;
    /**
     * 
     * @type {string}
     * @memberof ImageDto
     */
    'updatedAt'?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof ImageDto
     */
    'tags'?: Array<string> | null;
    /**
     * 
     * @type {string}
     * @memberof ImageDto
     */
    'url'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ImageDto
     */
    'thumbnail'?: string | null;
    /**
     * 
     * @type {number}
     * @memberof ImageDto
     */
    'height'?: number;
    /**
     * 
     * @type {number}
     * @memberof ImageDto
     */
    'width'?: number;
    /**
     * 
     * @type {number}
     * @memberof ImageDto
     */
    'size'?: number;
    /**
     * 
     * @type {boolean}
     * @memberof ImageDto
     */
    'hasAlpha'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof ImageDto
     */
    'mime'?: string | null;
}

