/* tslint:disable */
/* eslint-disable */
/**
 * PokerEvents.Api, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ImageUpdateDto
 */
export interface ImageUpdateDto {
    /**
     * 
     * @type {string}
     * @memberof ImageUpdateDto
     */
    'fileId'?: string | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof ImageUpdateDto
     */
    'removeAITags'?: Array<string> | null;
    /**
     * 
     * @type {string}
     * @memberof ImageUpdateDto
     */
    'webhookUrl'?: string | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof ImageUpdateDto
     */
    'extensions'?: Array<string> | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof ImageUpdateDto
     */
    'tags'?: Array<string> | null;
    /**
     * 
     * @type {string}
     * @memberof ImageUpdateDto
     */
    'customCoordinates'?: string | null;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof ImageUpdateDto
     */
    'customMetadata'?: { [key: string]: string; } | null;
}

