/* tslint:disable */
/* eslint-disable */
/**
 * PokerEvents.Api, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface LiveUpdateTableImportDto
 */
export interface LiveUpdateTableImportDto {
    /**
     * 
     * @type {number}
     * @memberof LiveUpdateTableImportDto
     */
    '_Position'?: number | null;
    /**
     * 
     * @type {string}
     * @memberof LiveUpdateTableImportDto
     */
    '_Player'?: string | null;
    /**
     * 
     * @type {number}
     * @memberof LiveUpdateTableImportDto
     */
    '_Table'?: number | null;
    /**
     * 
     * @type {number}
     * @memberof LiveUpdateTableImportDto
     */
    '_Seat'?: number | null;
    /**
     * 
     * @type {number}
     * @memberof LiveUpdateTableImportDto
     */
    '_ChipCounts'?: number | null;
    /**
     * 
     * @type {number}
     * @memberof LiveUpdateTableImportDto
     */
    '_Prize'?: number | null;
    /**
     * 
     * @type {number}
     * @memberof LiveUpdateTableImportDto
     */
    '_PrizeUsd'?: number | null;
}

