/* tslint:disable */
/* eslint-disable */
/**
 * PokerEvents.Api, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { DayImportDto } from './day-import-dto';
// May contain unused imports in some cases
// @ts-ignore
import { LiveUpdateImportDto } from './live-update-import-dto';
// May contain unused imports in some cases
// @ts-ignore
import { StateType } from './state-type';

/**
 * 
 * @export
 * @interface LiveReportingImportDto
 */
export interface LiveReportingImportDto {
    /**
     * 
     * @type {string}
     * @memberof LiveReportingImportDto
     */
    'name'?: string | null;
    /**
     * 
     * @type {StateType}
     * @memberof LiveReportingImportDto
     */
    'state'?: StateType;
    /**
     * 
     * @type {string}
     * @memberof LiveReportingImportDto
     */
    'slug'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof LiveReportingImportDto
     */
    'date'?: string;
    /**
     * 
     * @type {DayImportDto}
     * @memberof LiveReportingImportDto
     */
    'day'?: DayImportDto;
    /**
     * 
     * @type {Array<LiveUpdateImportDto>}
     * @memberof LiveReportingImportDto
     */
    'liveUpdates'?: Array<LiveUpdateImportDto> | null;
}



