/* tslint:disable */
/* eslint-disable */
/**
 * PokerEvents.Api, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface Metadata
 */
export interface Metadata {
    /**
     * 
     * @type {number}
     * @memberof Metadata
     */
    'height'?: number;
    /**
     * 
     * @type {number}
     * @memberof Metadata
     */
    'width'?: number;
    /**
     * 
     * @type {number}
     * @memberof Metadata
     */
    'size'?: number;
    /**
     * 
     * @type {string}
     * @memberof Metadata
     */
    'format'?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof Metadata
     */
    'hasColorProfile'?: boolean;
    /**
     * 
     * @type {number}
     * @memberof Metadata
     */
    'quality'?: number;
    /**
     * 
     * @type {number}
     * @memberof Metadata
     */
    'density'?: number;
    /**
     * 
     * @type {boolean}
     * @memberof Metadata
     */
    'hasTransparency'?: boolean;
    /**
     * 
     * @type {object}
     * @memberof Metadata
     */
    'exif'?: object;
    /**
     * 
     * @type {string}
     * @memberof Metadata
     */
    'pHash'?: string | null;
}

