/* tslint:disable */
/* eslint-disable */
/**
 * PokerEvents.Api, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { EventEntity } from './event-entity';

/**
 * 
 * @export
 * @interface PayoutEntity
 */
export interface PayoutEntity {
    /**
     * 
     * @type {string}
     * @memberof PayoutEntity
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof PayoutEntity
     */
    'eventId'?: string;
    /**
     * 
     * @type {number}
     * @memberof PayoutEntity
     */
    'position'?: number;
    /**
     * 
     * @type {number}
     * @memberof PayoutEntity
     */
    'prize'?: number;
    /**
     * 
     * @type {number}
     * @memberof PayoutEntity
     */
    'priceUsd'?: number;
    /**
     * 
     * @type {EventEntity}
     * @memberof PayoutEntity
     */
    'event'?: EventEntity;
}

