/* tslint:disable */
/* eslint-disable */
/**
 * PokerEvents.Api, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { ActualPrizeDto } from './actual-prize-dto';
// May contain unused imports in some cases
// @ts-ignore
import { PayoutDetailsDto } from './payout-details-dto';
// May contain unused imports in some cases
// @ts-ignore
import { PlayerSummaryDto } from './player-summary-dto';
// May contain unused imports in some cases
// @ts-ignore
import { RegistrationStatisticsDto } from './registration-statistics-dto';

/**
 * 
 * @export
 * @interface RegistrationDetailedDto
 */
export interface RegistrationDetailedDto {
    /**
     * 
     * @type {string}
     * @memberof RegistrationDetailedDto
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof RegistrationDetailedDto
     */
    'eventId'?: string;
    /**
     * 
     * @type {string}
     * @memberof RegistrationDetailedDto
     */
    'payoutId'?: string | null;
    /**
     * 
     * @type {number}
     * @memberof RegistrationDetailedDto
     */
    'position'?: number | null;
    /**
     * 
     * @type {ActualPrizeDto}
     * @memberof RegistrationDetailedDto
     */
    'prize'?: ActualPrizeDto;
    /**
     * 
     * @type {RegistrationStatisticsDto}
     * @memberof RegistrationDetailedDto
     */
    'statistics'?: RegistrationStatisticsDto;
    /**
     * 
     * @type {PlayerSummaryDto}
     * @memberof RegistrationDetailedDto
     */
    'player'?: PlayerSummaryDto;
    /**
     * 
     * @type {PayoutDetailsDto}
     * @memberof RegistrationDetailedDto
     */
    'payout'?: PayoutDetailsDto;
}

