/* tslint:disable */
/* eslint-disable */
/**
 * PokerEvents.Api, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { ChipCountUpdateEntity } from './chip-count-update-entity';
// May contain unused imports in some cases
// @ts-ignore
import { EventEntity } from './event-entity';
// May contain unused imports in some cases
// @ts-ignore
import { PayoutEntity } from './payout-entity';
// May contain unused imports in some cases
// @ts-ignore
import { PlayerEntity } from './player-entity';
// May contain unused imports in some cases
// @ts-ignore
import { RegistrationStatisticsDto } from './registration-statistics-dto';

/**
 * 
 * @export
 * @interface RegistrationEntity
 */
export interface RegistrationEntity {
    /**
     * 
     * @type {string}
     * @memberof RegistrationEntity
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof RegistrationEntity
     */
    'eventId'?: string;
    /**
     * 
     * @type {string}
     * @memberof RegistrationEntity
     */
    'playerId'?: string;
    /**
     * 
     * @type {string}
     * @memberof RegistrationEntity
     */
    'payoutId'?: string | null;
    /**
     * 
     * @type {number}
     * @memberof RegistrationEntity
     */
    'position'?: number | null;
    /**
     * 
     * @type {number}
     * @memberof RegistrationEntity
     */
    'prize'?: number | null;
    /**
     * 
     * @type {number}
     * @memberof RegistrationEntity
     */
    'prizeUsd'?: number | null;
    /**
     * 
     * @type {RegistrationStatisticsDto}
     * @memberof RegistrationEntity
     */
    'statistics'?: RegistrationStatisticsDto;
    /**
     * 
     * @type {EventEntity}
     * @memberof RegistrationEntity
     */
    'event'?: EventEntity;
    /**
     * 
     * @type {PlayerEntity}
     * @memberof RegistrationEntity
     */
    'player'?: PlayerEntity;
    /**
     * 
     * @type {PayoutEntity}
     * @memberof RegistrationEntity
     */
    'payout'?: PayoutEntity;
    /**
     * 
     * @type {Array<ChipCountUpdateEntity>}
     * @memberof RegistrationEntity
     */
    'chipCountUpdates'?: Array<ChipCountUpdateEntity> | null;
}

