/* tslint:disable */
/* eslint-disable */
/**
 * PokerEvents.Api, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface SeasonEntity
 */
export interface SeasonEntity {
    /**
     * 
     * @type {string}
     * @memberof SeasonEntity
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof SeasonEntity
     */
    'tourId'?: string;
    /**
     * 
     * @type {string}
     * @memberof SeasonEntity
     */
    'name'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SeasonEntity
     */
    'description'?: string | null;
    /**
     * 
     * @type {number}
     * @memberof SeasonEntity
     */
    'year'?: number;
    /**
     * 
     * @type {string}
     * @memberof SeasonEntity
     */
    'thmCode'?: string | null;
}

