/* tslint:disable */
/* eslint-disable */
/**
 * PokerEvents.Api, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @enum {string}
 */

export enum SectionType {
    Text = 'Text',
    ChipCount = 'ChipCount',
    Seating = 'Seating',
    Results = 'Results',
    Payout = 'Payout',
    HandHistory = 'HandHistory',
    Photo = 'Photo',
    Video = 'Video'
}



