/* tslint:disable */
/* eslint-disable */
/**
 * PokerEvents.Api, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { SeasonEntity } from './season-entity';

/**
 * 
 * @export
 * @interface TourEntity
 */
export interface TourEntity {
    /**
     * 
     * @type {string}
     * @memberof TourEntity
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof TourEntity
     */
    'name'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof TourEntity
     */
    'description'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof TourEntity
     */
    'abbreviation'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof TourEntity
     */
    'logoUrl'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof TourEntity
     */
    'websiteUrl'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof TourEntity
     */
    'thmId'?: string | null;
    /**
     * 
     * @type {Array<SeasonEntity>}
     * @memberof TourEntity
     */
    'seasons'?: Array<SeasonEntity> | null;
}

