/* tslint:disable */
/* eslint-disable */
/**
 * PokerEvents.Api, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface VenueImportData
 */
export interface VenueImportData {
    /**
     * 
     * @type {string}
     * @memberof VenueImportData
     */
    'name'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof VenueImportData
     */
    'url'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof VenueImportData
     */
    'country'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof VenueImportData
     */
    'alpha3Code'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof VenueImportData
     */
    'lat'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof VenueImportData
     */
    'lng'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof VenueImportData
     */
    'image'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof VenueImportData
     */
    'description'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof VenueImportData
     */
    'title'?: string | null;
}

