/* tslint:disable */
/* eslint-disable */
/**
 * PokerEvents.Api, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface VenueEntity
 */
export interface VenueEntity {
    /**
     * 
     * @type {string}
     * @memberof VenueEntity
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof VenueEntity
     */
    'name': string;
    /**
     * 
     * @type {string}
     * @memberof VenueEntity
     */
    'description'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof VenueEntity
     */
    'summary'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof VenueEntity
     */
    'countryIso'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof VenueEntity
     */
    'city'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof VenueEntity
     */
    'address'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof VenueEntity
     */
    'phone'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof VenueEntity
     */
    'email'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof VenueEntity
     */
    'websiteUrl'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof VenueEntity
     */
    'logoUrl'?: string | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof VenueEntity
     */
    'photos'?: Array<string> | null;
    /**
     * 
     * @type {string}
     * @memberof VenueEntity
     */
    'thmId'?: string | null;
}

